import type { AssetFile, Product, FolderNode } from '../types';

// ── Mock Products ──────────────────────────────────────────────────
export const mockProducts: Product[] = [
    {
        asin: 'B08X5JYZ',
        name: 'Red Velvet Pillow',
        driveFolderId: 'folder_001',
        fileCount: 8,
        lastUpload: new Date('2025-06-01'),
    },
    {
        asin: 'B09KZPQ2',
        name: 'Blue Water Bottle',
        driveFolderId: 'folder_002',
        fileCount: 5,
        lastUpload: new Date('2025-06-10'),
    },
    {
        asin: 'B07HNRX3',
        name: 'Bamboo Cutting Board',
        driveFolderId: 'folder_003',
        fileCount: 12,
        lastUpload: new Date('2025-05-20'),
    },
];

// ── Mock Folder Tree ───────────────────────────────────────────────
export const mockFolderTree: FolderNode[] = [
    {
        id: 'root',
        name: 'AmazonAssetManager',
        driveId: 'root_drive',
        parentId: null,
        type: 'subfolder',
        children: [
            {
                id: 'products',
                name: 'Products',
                driveId: 'products_drive',
                parentId: 'root',
                type: 'subfolder',
                children: [
                    {
                        id: 'folder_001',
                        name: 'B08X5JYZ-RedPillow',
                        driveId: 'folder_001_drive',
                        parentId: 'products',
                        type: 'product',
                        children: [
                            { id: 'f001_img', name: 'Images', driveId: 'f001_img_d', parentId: 'folder_001', type: 'subfolder', children: [] },
                            { id: 'f001_vid', name: 'Videos', driveId: 'f001_vid_d', parentId: 'folder_001', type: 'subfolder', children: [] },
                            { id: 'f001_copy', name: 'Copywriting', driveId: 'f001_copy_d', parentId: 'folder_001', type: 'subfolder', children: [] },
                            { id: 'f001_kw', name: 'Keywords', driveId: 'f001_kw_d', parentId: 'folder_001', type: 'subfolder', children: [] },
                        ],
                    },
                    {
                        id: 'folder_002',
                        name: 'B09KZPQ2-BlueBottle',
                        driveId: 'folder_002_drive',
                        parentId: 'products',
                        type: 'product',
                        children: [
                            { id: 'f002_img', name: 'Images', driveId: 'f002_img_d', parentId: 'folder_002', type: 'subfolder', children: [] },
                            { id: 'f002_vid', name: 'Videos', driveId: 'f002_vid_d', parentId: 'folder_002', type: 'subfolder', children: [] },
                        ],
                    },
                    {
                        id: 'folder_003',
                        name: 'B07HNRX3-CuttingBoard',
                        driveId: 'folder_003_drive',
                        parentId: 'products',
                        type: 'product',
                        children: [
                            { id: 'f003_img', name: 'Images', driveId: 'f003_img_d', parentId: 'folder_003', type: 'subfolder', children: [] },
                        ],
                    },
                ],
            },
            {
                id: 'learning',
                name: 'Learning',
                driveId: 'learning_drive',
                parentId: 'root',
                type: 'learning',
                children: [
                    { id: 'learn_ppc', name: 'PPC', driveId: 'learn_ppc_d', parentId: 'learning', type: 'subfolder', children: [] },
                    { id: 'learn_fba', name: 'FBA_Logistics', driveId: 'learn_fba_d', parentId: 'learning', type: 'subfolder', children: [] },
                    { id: 'learn_seo', name: 'SEO_Listing', driveId: 'learn_seo_d', parentId: 'learning', type: 'subfolder', children: [] },
                    { id: 'learn_photo', name: 'Photography', driveId: 'learn_photo_d', parentId: 'learning', type: 'subfolder', children: [] },
                ],
            },
            {
                id: 'archive',
                name: '_Archive',
                driveId: 'archive_drive',
                parentId: 'root',
                type: 'archive',
                children: [],
            },
        ],
    },
];

// ── Sample placeholder images (from picsum) ────────────────────────
const sampleThumbs = [
    'https://picsum.photos/seed/amz1/400/400',
    'https://picsum.photos/seed/amz2/400/400',
    'https://picsum.photos/seed/amz3/400/400',
    'https://picsum.photos/seed/amz4/400/400',
    'https://picsum.photos/seed/amz5/400/400',
    'https://picsum.photos/seed/amz6/400/400',
    'https://picsum.photos/seed/amz7/400/400',
    'https://picsum.photos/seed/pillow1/400/400',
    'https://picsum.photos/seed/pillow2/400/400',
    'https://picsum.photos/seed/bottle1/400/400',
    'https://picsum.photos/seed/bottle2/400/400',
    'https://picsum.photos/seed/board1/400/400',
];

// ── Mock Files ─────────────────────────────────────────────────────
export const mockFiles: AssetFile[] = [
    {
        id: '1', driveId: 'drive_1',
        name: 'IMG_B08X5JYZ_RED_MAIN_20250601.jpg', originalName: 'pillow_main.jpg',
        type: 'image', mimeType: 'image/jpeg', size: 2457600,
        asin: 'B08X5JYZ', productName: 'Red Velvet Pillow',
        category: 'Products/B08X5JYZ-RedPillow/Images',
        tags: ['main-image', 'hero', 'v2'],
        thumbnailUrl: sampleThumbs[0], webViewLink: '#', downloadUrl: '#',
        driveFolderId: 'f001_img', createdAt: new Date('2025-06-01'), updatedAt: new Date('2025-06-01'),
        uploadedBy: 'user@gmail.com', status: 'active',
    },
    {
        id: '2', driveId: 'drive_2',
        name: 'IMG_B08X5JYZ_RED_LIFESTYLE_20250601.jpg', originalName: 'pillow_lifestyle.jpg',
        type: 'image', mimeType: 'image/jpeg', size: 3145728,
        asin: 'B08X5JYZ', productName: 'Red Velvet Pillow',
        category: 'Products/B08X5JYZ-RedPillow/Images',
        tags: ['lifestyle', 'v2'],
        thumbnailUrl: sampleThumbs[1], webViewLink: '#', downloadUrl: '#',
        driveFolderId: 'f001_img', createdAt: new Date('2025-06-01'), updatedAt: new Date('2025-06-01'),
        uploadedBy: 'user@gmail.com', status: 'active',
    },
    {
        id: '3', driveId: 'drive_3',
        name: 'IMG_B08X5JYZ_INFOGRAPHIC_20250601.png', originalName: 'infographic.png',
        type: 'image', mimeType: 'image/png', size: 4194304,
        asin: 'B08X5JYZ', productName: 'Red Velvet Pillow',
        category: 'Products/B08X5JYZ-RedPillow/Images',
        tags: ['infographic', 'a-plus'],
        thumbnailUrl: sampleThumbs[2], webViewLink: '#', downloadUrl: '#',
        driveFolderId: 'f001_img', createdAt: new Date('2025-06-02'), updatedAt: new Date('2025-06-02'),
        uploadedBy: 'user@gmail.com', status: 'active',
    },
    {
        id: '4', driveId: 'drive_4',
        name: 'VID_B08X5JYZ_DEMO_20250601.mp4', originalName: 'demo_video.mp4',
        type: 'video', mimeType: 'video/mp4', size: 52428800,
        asin: 'B08X5JYZ', productName: 'Red Velvet Pillow',
        category: 'Products/B08X5JYZ-RedPillow/Videos',
        tags: ['demo', 'listing-video'],
        thumbnailUrl: sampleThumbs[3], webViewLink: '#', downloadUrl: '#',
        driveFolderId: 'f001_vid', createdAt: new Date('2025-06-01'), updatedAt: new Date('2025-06-01'),
        uploadedBy: 'user@gmail.com', status: 'active',
    },
    {
        id: '5', driveId: 'drive_5',
        name: 'TXT_B08X5JYZ_TITLE_V2_20250601.txt', originalName: 'title_copy.txt',
        type: 'text', mimeType: 'text/plain', size: 2048,
        asin: 'B08X5JYZ', productName: 'Red Velvet Pillow',
        category: 'Products/B08X5JYZ-RedPillow/Copywriting',
        tags: ['title', 'v2', 'optimized'],
        thumbnailUrl: '', webViewLink: '#', downloadUrl: '#',
        driveFolderId: 'f001_copy', createdAt: new Date('2025-06-01'), updatedAt: new Date('2025-06-03'),
        uploadedBy: 'user@gmail.com', status: 'active',
    },
    {
        id: '6', driveId: 'drive_6',
        name: 'TXT_B08X5JYZ_BULLETS_V1_20250601.txt', originalName: 'bullets.txt',
        type: 'text', mimeType: 'text/plain', size: 3072,
        asin: 'B08X5JYZ', productName: 'Red Velvet Pillow',
        category: 'Products/B08X5JYZ-RedPillow/Copywriting',
        tags: ['bullets', 'v1'],
        thumbnailUrl: '', webViewLink: '#', downloadUrl: '#',
        driveFolderId: 'f001_copy', createdAt: new Date('2025-06-01'), updatedAt: new Date('2025-06-01'),
        uploadedBy: 'user@gmail.com', status: 'active',
    },
    {
        id: '7', driveId: 'drive_7',
        name: 'XLS_B08X5JYZ_KEYWORDS_20250601.xlsx', originalName: 'keywords.xlsx',
        type: 'xlsx', mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', size: 102400,
        asin: 'B08X5JYZ', productName: 'Red Velvet Pillow',
        category: 'Products/B08X5JYZ-RedPillow/Keywords',
        tags: ['keywords', 'research'],
        thumbnailUrl: '', webViewLink: '#', downloadUrl: '#',
        driveFolderId: 'f001_kw', createdAt: new Date('2025-06-01'), updatedAt: new Date('2025-06-01'),
        uploadedBy: 'user@gmail.com', status: 'active',
    },
    {
        id: '8', driveId: 'drive_8',
        name: 'IMG_B09KZPQ2_BLUE_MAIN_20250610.jpg', originalName: 'bottle_main.jpg',
        type: 'image', mimeType: 'image/jpeg', size: 1843200,
        asin: 'B09KZPQ2', productName: 'Blue Water Bottle',
        category: 'Products/B09KZPQ2-BlueBottle/Images',
        tags: ['main-image', 'hero'],
        thumbnailUrl: sampleThumbs[9], webViewLink: '#', downloadUrl: '#',
        driveFolderId: 'f002_img', createdAt: new Date('2025-06-10'), updatedAt: new Date('2025-06-10'),
        uploadedBy: 'user@gmail.com', status: 'active',
    },
    {
        id: '9', driveId: 'drive_9',
        name: 'IMG_B09KZPQ2_LIFESTYLE_20250610.jpg', originalName: 'bottle_lifestyle.jpg',
        type: 'image', mimeType: 'image/jpeg', size: 2621440,
        asin: 'B09KZPQ2', productName: 'Blue Water Bottle',
        category: 'Products/B09KZPQ2-BlueBottle/Images',
        tags: ['lifestyle'],
        thumbnailUrl: sampleThumbs[10], webViewLink: '#', downloadUrl: '#',
        driveFolderId: 'f002_img', createdAt: new Date('2025-06-10'), updatedAt: new Date('2025-06-10'),
        uploadedBy: 'user@gmail.com', status: 'active',
    },
    {
        id: '10', driveId: 'drive_10',
        name: 'VID_B09KZPQ2_UNBOXING_20250610.mp4', originalName: 'unboxing.mp4',
        type: 'video', mimeType: 'video/mp4', size: 78643200,
        asin: 'B09KZPQ2', productName: 'Blue Water Bottle',
        category: 'Products/B09KZPQ2-BlueBottle/Videos',
        tags: ['unboxing', 'review'],
        thumbnailUrl: sampleThumbs[4], webViewLink: '#', downloadUrl: '#',
        driveFolderId: 'f002_vid', createdAt: new Date('2025-06-10'), updatedAt: new Date('2025-06-10'),
        uploadedBy: 'user@gmail.com', status: 'active',
    },
    {
        id: '11', driveId: 'drive_11',
        name: 'IMG_B07HNRX3_MAIN_20250520.jpg', originalName: 'board_main.jpg',
        type: 'image', mimeType: 'image/jpeg', size: 2097152,
        asin: 'B07HNRX3', productName: 'Bamboo Cutting Board',
        category: 'Products/B07HNRX3-CuttingBoard/Images',
        tags: ['main-image', 'hero', 'premium'],
        thumbnailUrl: sampleThumbs[11], webViewLink: '#', downloadUrl: '#',
        driveFolderId: 'f003_img', createdAt: new Date('2025-05-20'), updatedAt: new Date('2025-05-20'),
        uploadedBy: 'user@gmail.com', status: 'active',
    },
    {
        id: '12', driveId: 'drive_12',
        name: 'LEARN_PPC_BASICS_2025.pdf', originalName: 'ppc_guide.pdf',
        type: 'pdf', mimeType: 'application/pdf', size: 5242880,
        asin: null, productName: null,
        category: 'Learning/PPC',
        tags: ['ppc', 'basics', 'guide'],
        thumbnailUrl: '', webViewLink: '#', downloadUrl: '#',
        driveFolderId: 'learn_ppc', createdAt: new Date('2025-01-15'), updatedAt: new Date('2025-01-15'),
        uploadedBy: 'user@gmail.com', status: 'active',
    },
    {
        id: '13', driveId: 'drive_13',
        name: 'LEARN_PPC_ADVANCED_2025.mp4', originalName: 'ppc_advanced.mp4',
        type: 'video', mimeType: 'video/mp4', size: 157286400,
        asin: null, productName: null,
        category: 'Learning/PPC',
        tags: ['ppc', 'advanced', 'course'],
        thumbnailUrl: sampleThumbs[5], webViewLink: '#', downloadUrl: '#',
        driveFolderId: 'learn_ppc', createdAt: new Date('2025-02-01'), updatedAt: new Date('2025-02-01'),
        uploadedBy: 'user@gmail.com', status: 'active',
    },
    {
        id: '14', driveId: 'drive_14',
        name: 'LEARN_FBA_SHIPMENT_GUIDE_20250301.pdf', originalName: 'fba_guide.pdf',
        type: 'pdf', mimeType: 'application/pdf', size: 3145728,
        asin: null, productName: null,
        category: 'Learning/FBA_Logistics',
        tags: ['fba', 'shipment', 'guide'],
        thumbnailUrl: '', webViewLink: '#', downloadUrl: '#',
        driveFolderId: 'learn_fba', createdAt: new Date('2025-03-01'), updatedAt: new Date('2025-03-01'),
        uploadedBy: 'user@gmail.com', status: 'active',
    },
    {
        id: '15', driveId: 'drive_15',
        name: 'IMG_B08X5JYZ_WHITE_BG_20250605.jpg', originalName: 'pillow_white_bg.jpg',
        type: 'image', mimeType: 'image/jpeg', size: 1572864,
        asin: 'B08X5JYZ', productName: 'Red Velvet Pillow',
        category: 'Products/B08X5JYZ-RedPillow/Images',
        tags: ['white-bg', 'amazon-ready'],
        thumbnailUrl: sampleThumbs[7], webViewLink: '#', downloadUrl: '#',
        driveFolderId: 'f001_img', createdAt: new Date('2025-06-05'), updatedAt: new Date('2025-06-05'),
        uploadedBy: 'user@gmail.com', status: 'active',
    },
    {
        id: '16', driveId: 'drive_16',
        name: 'IMG_B08X5JYZ_CLOSEUP_20250605.jpg', originalName: 'pillow_closeup.jpg',
        type: 'image', mimeType: 'image/jpeg', size: 2891776,
        asin: 'B08X5JYZ', productName: 'Red Velvet Pillow',
        category: 'Products/B08X5JYZ-RedPillow/Images',
        tags: ['closeup', 'detail', 'texture'],
        thumbnailUrl: sampleThumbs[8], webViewLink: '#', downloadUrl: '#',
        driveFolderId: 'f001_img', createdAt: new Date('2025-06-05'), updatedAt: new Date('2025-06-05'),
        uploadedBy: 'user@gmail.com', status: 'active',
    },
];

// ── Mock user ──────────────────────────────────────────────────────
export const mockUser = {
    uid: 'mock_uid_001',
    email: 'seller@amazon-pro.com',
    displayName: 'Amazon Seller',
    photoURL: 'https://ui-avatars.com/api/?name=Amazon+Seller&background=FF9900&color=fff&size=128',
    accessToken: 'mock_access_token',
};
